var = "HII  "
#print(len(var))
print(var.find("h"))
print(var.capitalize())
print(var.upper())
print(var.lower())
print(var.isdigit())
print("number of I's = "+str(var.count("I")))
print("true or false = "+str(var.isalpha()))
print("replacing the character H with k =  "+str(var.replace("H", "k")))
print(var*10)